easy_admin:
    site_name: 'Revealpic'
    entities:
        User:
            class: App\Entity\User
            label: 'User'
        Page:
            class: App\Entity\Page
            label: 'Page'
            list:
                fields:
                    - { property: 'slug', template: 'admin/slug.html.twig' }
                    - { property: 'pictureFile', template: 'admin/vich.uploader_image.html.twig' }
                    - updatedAt
                    - viewCount
                    - pieces
            form:
                fields:
                    - { property: 'pictureFile', type: 'vich_image' }
        Piece:
            class: App\Entity\Piece
            label: 'Piece'
            disabled_actions: ['new']
    list:
        title: 'Liste des %%entity_label%%(s)'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
