parameters:
    locale: 'en'
    app.pictures_directory_path: '%kernel.project_dir%/assets/pictures'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\PictureService:
        bind:
            $picturesDirectoryPath: '%app.pictures_directory_path%'

    App\EventListener\PageSubscriber:
        tags:
        - { name: doctrine.event_subscriber, connection: default }
